### ISSUE TITLE
some tweets / images are missing

### ISSUE THREAD

**Issue by drandreaskrueger** [geduldig/TwitterGeoPics#8]
example:

    python -u -m TwitterGeoPics.SearchOldTweets -words '#DevconLiveStream' -photo_dir ./photos/ -oauth twitterapi-oauth.txt 

collects this tweet [926614818886422528](https://twitter.com/drandreaskruger/status/926614818886422528) which contains an image

but that image is not downloaded. How come?

**Comment by geduldig** [comment]
The TwitterAPI (which TwitterGeoPics uses) has a nice command line utility you can get from TwitterAPI/examples -- https://github.com/geduldig/TwitterAPI/tree/master/examples/cli.

With cli.py you can execute any Twitter request, such as getting the tweet you mentioned. This command nicely formats the raw json tweet:

python cli.py -e statuses/show/:926614818886422528 -i 2

This command prints just the value of the `media_url_https` field:
python cli.py -e statuses/show/:926614818886422528 -f media_url_https

You will see it prints nothing for this tweet. So, that's why you didn't get an image. There was none where TwitterGeoPics is looking for one. You tweeted this. How did you embed the image? If for instance, your embedded a url, I think Twitter will try to render it as an embedded image. Not sure in your case. Look at the raw json. You might need to add something to my code to get this type of embedded image.
